--- 
abstract: livedoor Auth API for Catalyst.
author: Tomohiro IKEBE <ikebe@shebang.jp>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.65
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Catalyst-Plugin-Authentication-Credential-Livedoor
no_index: 
  directory: 
    - inc
    - t
requires: 
  Catalyst: 5.700
  WebService::Livedoor::Auth: 0.01
version: 0.03
